name: Python Testing

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  test_pykokkos:
    strategy:
      matrix:
        platform: [ubuntu-latest]
        python-version: ["3.8", "3.9", "3.10"]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade numpy mypy cmake pytest pybind11
      - name: Install pykokkos-base
        run: |
          cd /tmp
          git clone https://github.com/kokkos/pykokkos-base.git
          cd pykokkos-base
          mkdir build && cd build
          cmake -DENABLE_LAYOUTS=ON -DENABLE_MEMORY_TRAITS=OFF ../
          make -j
      - name: Install pykokkos
        run: |
          python -m pip install .
      - name: mypy check
        run: |
          mypy pykokkos
      - name: run tests
        run: |
          python runtests.py
